### ISSUE TITLE
After Laguage Change "No region found"

### ISSUE THREAD

**Issue by ace16vitamine** [shopwareLabs/SwagPaymentPaypal#5]
We changed the language from de_DE to de_LI and renamed de_DE to de_DE2 and de_LI to de_DE.

Now we get the message

Ups! Ein Fehler ist aufgetreten! Die nachfolgenden Hinweise sollten Ihnen weiterhelfen. No region found within the locale 'de' in engine/Library/Zend/Currency.php on line 561 Stack trace: #0 engine/Library/Zend/Currency.php(106): Zend_Currency->setLocale(Object(Zend_Locale)) #1 engine/Shopware/Components/DependencyInjection/Bridge/Currency.php(49): Zend_Currency->__construct('EUR', Object(Zend_Locale)) #2 var/cache/production_201608150941/proxies/ShopwareProductionda39a3ee5e6b4b0d3255bfef95601890afd80709ProjectContainer.php(443): Shopware\Components\DependencyInjection\Bridge\Currency->factory(Object(ShopwareProductionda39a3ee5e6b4b0d3255bfef95601890afd80709ProjectContainer), Object(Zend_Locale)) #3 vendor/symfony/dependency-injection/Container.php(314): ShopwareProductionda39a3ee5e6b4b0d3255bfef95601890afd80709ProjectContainer->getCurrencyService() #4 engine/Shopware/Components/DependencyInjection/Container.php(182): Symfony\Component\DependencyInjection\Container->get('currency', 2) #5 engine/Shopware/Components/DependencyInjection/Container.php(88): Shopware\Components\DependencyInjection\Container->doLoad('currency') #6 engine/Shopware/Application.php(368): Shopware\Components\DependencyInjection\Container->has('Currency') #7 engine/Shopware/Plugins/Community/Frontend/SwagPaymentPaypal/Controllers/Backend/PaymentPaypal.php(189): Shopware->__call('Currency', Array) #8 engine/Shopware/Plugins/Community/Frontend/SwagPaymentPaypal/Controllers/Backend/PaymentPaypal.php(189): Shopware->Currency() #9 engine/Library/Enlight/Controller/Action.php(159): Shopware_Controllers_Backend_PaymentPaypal->getListAction() #10 engine/Library/Enlight/Controller/Dispatcher/Default.php(523): Enlight_Controller_Action->dispatch('getListAction') #11 engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) #12 engine/Shopware/Kernel.php(176): Enlight_Controller_Front->dispatch() #13 vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 engine/Shopware/Components/HttpCache/AppCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL) #15 vendor/symfony/http-kernel/HttpCache/HttpCache.php(258): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #16 engine/Shopware/Components/HttpCache/AppCache.php(103): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #17 shopware.php(101): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #18 {main}

**Comment by mitelg** [comment]
Hi @ace16vitamine 
I created a ticket for that in our issue tracker https://issues.shopware.com/#/issues/PT-6669
best regards
